### ISSUE TITLE
2.19 Initial test VR menu unresponsive

### ISSUE THREAD

**Issue by Jimbasaur** [phileday/Festoon#100]
No menu buttons working in VR

**Comment by NicholasWaterton** [comment]
I'm also having this issue. Menu buttons etc work from the desktop however almost no functionality is accessible from VR, except for switching seat, bringing up the 'VR dashboard', and stepping through video with the right controller stick.

video:
https://www.youtube.com/watch?v=yJbKnS4ZNCE&feature=youtu.be

**Comment by phileday** [comment]
This is caused by the None VR version I've just implemented. I'm fixing it and will upload a new version now.
