### ISSUE TITLE
2.19 Force desktop controls in VR view not working

### ISSUE THREAD

**Issue by Jimbasaur** [phileday/Festoon#101]
I expected to be able to move my mouse to look around once 'force desktop control' was selected but it was unresponsive.

I have been getting an error on steam regarding some add ons being blocked, I dont know if that might relevent?

**Comment by Jimbasaur** [comment]
Im an idiot. Its middle mouse button isnt it. 
Is there any reason it couldnt be left click? 

I think it could be a good idea to have small key in the bottom corner saying what the button mapping for the mouse is. With an option to turn it off.

**Comment by phileday** [comment]
There was a reason as the left mouse button is used for right click and other functions on the main window so it was easier to go for the middle button as it doesn't interfere with anything. In saying that you're right and I've added the left click to the movement controls.

Let me know if it has any knock on effects.
