### ISSUE TITLE
Lights bar visible over main desktop view port

### ISSUE THREAD

**Issue by Jimbasaur** [phileday/Festoon#102]
Lights bar is constantly visible over the media panel, no way to move it or switch it off. Maybe just have it running along the bottom of th
![image](https://user-images.githubusercontent.com/69035669/89019851-e05a2700-d315-11ea-9c1a-2e9f801699a8.png)

**Comment by NicholasWaterton** [comment]
I'd like to second this comment - it feels a little bit intrusive

**Comment by phileday** [comment]
Thanks for letting me know. I only added that yesterday so I've gone back in and redesigned it. I'll be updating again today and it will hopefully be fixed (it will defaintly be redesigned whether I break it in a different way).

**Comment by phileday** [comment]
The anchor was wrong. I'm redesigning it for the next update today.

**Comment by phileday** [comment]
Update, updated.
