### ISSUE TITLE
2.19_bug_offset when setting start area marker for the first time

### ISSUE THREAD

**Issue by NicholasWaterton** [phileday/Festoon#104]
It appears further down the timeline than expected. This only happened the first time I set it, after that it set at the current time.

video:
https://www.youtube.com/watch?v=0USO8oO16GE&feature=youtu.be

**Comment by phileday** [comment]
What resolution is your display and what scale have you got under the view menu?

**Comment by phileday** [comment]
I'm having a real problem recreating this. I seem to get it to fail once in a million. I've changed the code which might help but without being able to check it it's just a guess.

It'll be in the next update so see if it helps.

Actually is this very consistent for you?

**Comment by NicholasWaterton** [comment]
1920*1080 monitor
80% scale in Festoon
I've just tried to recreate this and it worked perfectly.

**Comment by phileday** [comment]
I've just updated the player so maybe that fixed it?
