### ISSUE TITLE
2.19_bug_incorrectly initialised Media Panel menu item in right-click menu

### ISSUE THREAD

**Issue by NicholasWaterton** [phileday/Festoon#105]
When using the right-click menu to switch from VR View to the Media Panel, the Media Panel radio button was initially set 'on', and the VR View button was 'off', which was the wrong way round. Switching between them fixed the issue.

video:
https://www.youtube.com/watch?v=rndwMQn9uzQ&feature=youtu.be

**Comment by phileday** [comment]
I'm not seeing this so maybe one of the other issues caused this to fail.

As I'll be uploading again today can you test to see if this happens again?

**Comment by NicholasWaterton** [comment]
I've just tried again and it is the same issue, so it seems to be persistent. I believe I'm using the updated Festoon (2.2).
![image](https://user-images.githubusercontent.com/62999153/89046869-7ce7ed80-d345-11ea-910c-f07ae80274dd.png)

**Comment by phileday** [comment]
I think I've found the issue. It only happens when in none vr mode.

I think I've fixed it for the next update.
