### ISSUE TITLE
2.19_bug_inconsistent 'snapshot saved' messages from Mirror mode

### ISSUE THREAD

**Issue by NicholasWaterton** [phileday/Festoon#106]
When saving a snapshot from Mirror mode, two messages appear on the desktop, one in the centre, one in the upper-left, indicating the name and file path. The centre one was incorrect, the upper-left one was correct.

video:
https://www.youtube.com/watch?v=GsFRMaia0F0&feature=youtu.be

**Comment by phileday** [comment]
Fixed for next release.
