### ISSUE TITLE
2.21_bug_Loop area unavailable

### ISSUE THREAD

**Issue by NicholasWaterton** [phileday/Festoon#113]
There doesn't seem to be a way to make use of the playback area. The VR playback panel has no loop button, and the desktop's loop button doesn't appear to function.

video:
https://youtu.be/_G4z0TNFdjY

**Comment by phileday** [comment]
This is an odd one.

The loop button in my version is available on the VR playback and also works as you would expect. 

Posibily I added this after uploading the last build or there might be a problem with your setup.

I'm going to leave this bug open and if you find that it still works in the same way could you send me the roaming folder located here:

C:\Users\%username%\AppData\Roaming\Festoon

**Comment by NicholasWaterton** [comment]
Hi Philippa, I've tried this again this morning and I am having the same issue. I've emailed you the Festoon folder from the directory you specified

**Comment by phileday** [comment]
Fixed for next release.
