### ISSUE TITLE
2.21_bug_Menu flipping

### ISSUE THREAD

**Issue by NicholasWaterton** [phileday/Festoon#114]
Dragging the VR menu to the zenith and nadir of the view area can break their orientation. Clicking on it again resets to the correct orientation

video:
https://youtu.be/zv0UVyCep-4

**Comment by phileday** [comment]
Looking into this it appears to work as expected when grabbing the middle. Well it still flips upside down but in truth that's as expected and is most evident when using the flat dome as you can be facing the other way completely and if it didn't flip it would be upside down.

After saying that if you don't grab the window in the middle it starts to look really weird and rotates in a way that doesn't seem right. 

One solution to this is that where ever you grab the window it jumps to the middle of the bar. Do you think this would be a good solution?

**Comment by NicholasWaterton** [comment]
I've just had another go. As you say, when you grab the panel from the middle it works absolutely fine. Do you mean that the cursor would jump to the middle of the bar when you grab the window? That sounds promising.
