### ISSUE TITLE
2.23_bug_In cinema, changing seats right from front-right chair does not jump to front-left chair

### ISSUE THREAD

**Issue by NicholasWaterton** [phileday/Festoon#126]
Unlike other edges of the seating, this particular one seems to be clamped, so it is not possible to jump from the front-right seat to the front-left seat by pushing right on the control stick

**Comment by phileday** [comment]
As I've clamped the seats so it doesn't loop around I think this issue is no longer relivant.

Open the issue again if I've miss understood.
