### ISSUE TITLE
2.23_QOL_I wish that 'loop media' was still available when 'continue to next media when finished' was on

### ISSUE THREAD

**Issue by NicholasWaterton** [phileday/Festoon#127]

**Comment by phileday** [comment]
What's the reason for this?

If the continue to next is on then loop doesn't work as it doesn't loop at the end but goes on to the next media.

How should this work? Give me a suggestion on what should happen here and I'll implement it.

**Comment by NicholasWaterton** [comment]
Ok here's the thought process, I apologise that it's a bit nitpicky:

I understand what you mean. The reason is that, currently, loop media is the only way to loop through the play area determined by the start/end markers. If looping the play area and looping the entire clip were separate buttons, then I don't believe there would be an issue. 

Here's where I imagine it would be useful: you're a director reviewing a lot of shots, you're watching a playlist with 'continue to next...' active, you see something of interest in a certain shot (probably happens a lot), you set the start/end area markers and toggle on 'loop play area' to watch it a couple of times, then toggle off 'loop play area' to continue your playlist. You can do this now, but you also need to toggle off 'continue to next' before looping and toggle it back on after looping, and sometimes there's extra faffing because (for me) there's confusion about why the loop button is disabled.

I think it's worth adding an extra button to streamline a process that could be a large part of what Festoon is used for.

Anyway this was a long explanation. I hope I'm not barking up the wrong tree here.

**Comment by phileday** [comment]
Thanks, I understand the problem now.

I'll look at a way to fix this whether to enable the loop again or whether to add a loop button for markers.
