### ISSUE TITLE
2.23_bug_initial position up in the air, not sure how to get down

### ISSUE THREAD

**Issue by NicholasWaterton** [phileday/Festoon#128]
This is an issue when using Festoon in desktop mode without VR. In this instance my headset isn't plugged in so I don't have access to the reset view button.

![image](https://user-images.githubusercontent.com/62999153/90492458-1f231600-e139-11ea-9c21-917bf5425fce.png)

**Comment by phileday** [comment]
Good catch. I've managed to fix this for the next update.
