### ISSUE TITLE
Festoon Multiplayer Beta Desktop controls and placement

### ISSUE THREAD

**Issue by Jimbasaur** [phileday/Festoon#131]
Just tried the beta, selected run desktop only when prompted by steam. Mouse didnt move the view, and selecting 'force desktop controls' seemed to place the pov outside the dome

**Comment by phileday** [comment]
I'm not getting this issue so I'm wondering if it might be settings in the ini files that exist from previous testing.

Could you send me your roaming folder C:\Users\%username%\AppData\Roaming\Festoon

and delete it and try again?
