### ISSUE TITLE
2.24_bug_File>Save Snapshot: Festoon gets stuck

### ISSUE THREAD

**Issue by NicholasWaterton** [phileday/Festoon#135]
When testing 'File>Save Snapshot', Festoon's desktop interface was blocked by message "Saving C:\Users\Greg\Desktop\Snapshot.png" until I closed Festoon. This test was attempting to overwrite an existing image. The 'Date modified' indicates that the image was not overwritten.

video:
https://youtu.be/svrddft56qM

**Comment by phileday** [comment]
Frustratingly I can't recreate this. I think it failed because the previous file couldn't be deleted so it errored. Until I can come up with a way to make this error I'll have to leave this problem.
