### ISSUE TITLE
2.29_marker ticks visible on timeline when no media is loaded

### ISSUE THREAD

**Issue by NicholasWaterton** [phileday/Festoon#153]
![Marker ticks visible on timeline when no media loaded](https://user-images.githubusercontent.com/62999153/95341619-5ba7fe00-08ae-11eb-80ba-b873f0e70e45.png)

**Comment by NicholasWaterton** [comment]
In this example only one tick is visible nearly the beginning of the timeline

**Comment by phileday** [comment]
How did you remove the media when there was no media loaded and a marker tick?

I'm having difficulty recreating this one.
