### ISSUE TITLE
When saving presets in VR, "enter text" box not accessible by IRL keyboard or oculus floating keyboard

### ISSUE THREAD

**Issue by NicholasWaterton** [phileday/Festoon#37]

**Comment by phileday** [comment]
I didn't know that there was a floating keyboard you could use in VR without programming it in.

I'll look at adding one so that's the default/

**Comment by NicholasWaterton** [comment]
Only the one that is used for Virtual Desktop. I thought it was worth a try.

**Comment by phileday** [comment]
An in app keyboard has been created so this should work in the next version uploaded today.
