### ISSUE TITLE
When in VR: unable to exit environment "save as.." window, other buttons and windows unresponsive after opening this window

### ISSUE THREAD

**Issue by NicholasWaterton** [phileday/Festoon#38]

**Comment by phileday** [comment]
"Save as" which one are you referring too? In VR, In the file menu?

**Comment by NicholasWaterton** [comment]
Apologies for the vague feedback!

**Comment by phileday** [comment]
Doesn't the "X" in the top right hand corner not close that window down?

**Comment by NicholasWaterton** [comment]
It doesn't. For a demo check the video I posted on Basecamp, it's at around 00:50

**Comment by phileday** [comment]
Ah I think I know where I'm getting confused. It's in the Colour adjustment that you can't close the window isn't it not the Custom environments.

The video was very useful by the way :)

**Comment by phileday** [comment]
I've added a keyboard to the save which should fix this problem. It'll be in the next update so I'll close it.

If the changes after the new update don't work let me know.
