### ISSUE TITLE
Request: an indication that circular chair arrangement is not available unless dome tilt is 0 would save some confusion

### ISSUE THREAD

**Issue by NicholasWaterton** [phileday/Festoon#41]

**Comment by phileday** [comment]
Will be added in next update.

**Comment by phileday** [comment]
I've done this in the desktop UI not the VR. I'll look at VR tomorrow.

**Comment by phileday** [comment]
So there's a tootip thing added to the Desktop UI and the button greys out. In VR I've made sure the options greys out as well. I'm going to imagine this is good enough for now and close the issue.
