### ISSUE TITLE
Bug: mirror image not displaying on dome (just a purple card with white cog)

### ISSUE THREAD

**Issue by NicholasWaterton** [phileday/Festoon#44]
See video on Basecamp for demo

**Comment by phileday** [comment]
I've checked with the version I'm working on and I don't get the same results. That might be because I've fixed it in the travels I've had over the code over the last few days so I'll upload the new version and let me know if this still happens.

**Comment by NicholasWaterton** [comment]
I must admit that when trying to recreate this it worked perfectly

**Comment by phileday** [comment]
There's a good chance that's because I've updated it :)

**Comment by phileday** [comment]
I've close the issue for now until it rears its head again.
