### ISSUE TITLE
Mirroring: multicoloured glitch

### ISSUE THREAD

**Issue by NicholasWaterton** [phileday/Festoon#45]
![image](https://user-images.githubusercontent.com/62999153/82205183-159dce00-98fe-11ea-8458-e9f5c5fa0c92.png)
I first noticed this issue a few days ago, now all mirroring is in funky colours.

**Comment by phileday** [comment]
Hi

It looks like the options have been changed in the colour adjustment settings. Right click and reset colour adjustment to be sure.

The colour adjustment that you can use of videos also works on Mirroring so there is a good chance it's that. If there is still a problem let me know.

Philippa

**Comment by NicholasWaterton** [comment]
*facepalm* yes that was it, thank you so much :D

**Comment by phileday** [comment]
No problem. One less thing to fix :)
