### ISSUE TITLE
marker still drawn on dome when dragging menu panel in VR mode

### ISSUE THREAD

**Issue by NicholasWaterton** [phileday/Festoon#46]
I know that this is because the marker is still activated, however I believe it may be more intuitive if the marker draw is temporarily disabled while menu panels are being moved. Please see video on this page for demo: https://3.basecamp.com/3145700/buckets/12067062/messages/2682986048#__recording_2687553338

**Comment by phileday** [comment]
Thanks.

I've found the bug and fixed for the next version.
