### ISSUE TITLE
feature request: option to use markers in mirror mode

### ISSUE THREAD

**Issue by NicholasWaterton** [phileday/Festoon#51]

**Comment by phileday** [comment]
How would this work as there is no timeline for mirror mode? Would it be one frame?

**Comment by NicholasWaterton** [comment]
Yes, exactly. One of the uses I've found for mirror mode is testing proxy environments from Blender. The ability to sketch props and characters and such over these would be a huge help while storyboarding for instance. One frame that you could then save to disk would be a lovely feature in my opinion.
