### ISSUE TITLE
feature request: fullscreen preview, no menu-items

### ISSUE THREAD

**Issue by TrickAnim** [phileday/Festoon#54]
I would like to use it to make pre-vis videos. A rendering system would be even better but probably overkill!

**Comment by phileday** [comment]
In what way were you thinking? using the marker system?

**Comment by TrickAnim** [comment]
To render? 
As in: set a start marker and end marker of the area you want to render and then export?

Would this take into account any ‘looking around’ I did with my mouse or headset input?

A quick fix would be to allow full screen and then I could screen record with OBS?

**Comment by phileday** [comment]
Just looking over this. You can go full screen by double clicking on the media window. Is this what you want at the moment?

**Comment by TrickAnim** [comment]
Unless I'm missing something, this keeps some of the GUI on screen? (Play-bar and navigathion widget etc)
If I wanted to make a good pre-vis video it would be good to press a key and everything is hidden, including the mouse.

Then I could record my screen with OBS and play through a fulldome video with a better representation of what it might look like in situ.

I don't know how hard this is or if anyone else would find it useful so it might not be worth your time!

**Comment by phileday** [comment]
The controls top and bottom disappear after a few seconds of not using the mouse in Festoon. Or at least should. Unless it isn't :)

**Comment by TrickAnim** [comment]
Yeah they do, that all works fine - but then if I want to move the camera they pop back up again. Also it would be good to hide the cursor while I still have control of the camera

**Comment by phileday** [comment]
Can I confirm this is for creating tutorials? So something I could make as a one off?

If so I could have it so that when it's fullscreen I could force the menus to not be there and hide the cursor? Would that work?

I could then upload a special version for this one instance.

**Comment by TrickAnim** [comment]
In my case I was going to use it for my showreel but I thought it might be useful for anything that is going out to the public to show off fulldome work

If you're just adding it as a one-off feature for me then don't worry about it - It's not pressing and there's probably many more important features
