### ISSUE TITLE
Bug report: when headset is off, refresh rate becomes choppy

### ISSUE THREAD

**Issue by NicholasWaterton** [phileday/Festoon#55]
This includes video playback and drawing markers. Please check out the video below (it's unlisted)
https://youtu.be/CQTx9hyd4rc

**Comment by phileday** [comment]
Hi

This is a weird one and one that was the problem with video sharing.

I'm going to look into it but it seems to be an Oculus problem. maybe the Oculus drivers need updating in Unity3D. 

Philippa
