### ISSUE TITLE
bug report: locked VR marker options in mirror mode

### ISSUE THREAD

**Issue by NicholasWaterton** [phileday/Festoon#61]
This feedback assumes that Mirror mode is supposed to have markers at this time.
VR marker options are locked in Mirror mode, except for 'drawing on' (pencil icon).
https://youtu.be/Uqwfm3ugqOw

**Comment by phileday** [comment]
I can see the issue. Thanks for the video.

I need to come up with a marker system for Mirror mode so I'll look at that today and try and find a way to allow markers. Not sure how I'm going to do it as where would the markers for mirror mode be save. I'll try and figure out something though :)
