### ISSUE TITLE
2.17 bug: VR Media List and Playback panel buttons unresponsive (sometimes)

### ISSUE THREAD

**Issue by NicholasWaterton** [phileday/Festoon#88]
When no media was loaded, I wasn't able to select media from the VR Media List, or press play via the VR Playback panel. Pressing the new play button on the VR Dashboard seemed to unlock VR Media List and Playback panel buttons, then I was able to use them again

video:
https://www.youtube.com/watch?v=LHeT-wBDVVY&feature=youtu.be

**Comment by phileday** [comment]
Yep this is wrong. The playback panel should be locked but not the media list as you should be able to select from that list. This will be fixed in the next update :)
