### ISSUE TITLE
2.17 bug: mark area start/end markers offset from correct position

### ISSUE THREAD

**Issue by NicholasWaterton** [phileday/Festoon#89]
Blue markers not appearing in line with current time when 'mark area start/end' button is clicked - they tend to appear a bit ahead of the current time. In the video you can also see that hitting the 'mark area start' button caused the end marker to refresh outside the VR Playback panel.

video:
https://www.youtube.com/watch?v=Vl4ureLqEKQ&feature=youtu.be

**Comment by phileday** [comment]
I'm having difficultly recreating this so I'll have to work on it once I've managed to work out how to break it.
