### ISSUE TITLE
2.17 bug(?): 'toolbar>View' doesn't give access to equirectangular environment

### ISSUE THREAD

**Issue by NicholasWaterton** [phileday/Festoon#92]
I believe that access to all: 'Standard Dome'; 'Flat Dome'; 'Cinema' and 'Equirectangular', would be most convenient

**Comment by phileday** [comment]
It's lucky you spotted this as the custom dome was actually accessible under that menu.

I've added the options to switch between the different presets as well so that's looking better :)
